### ISSUE TITLE
 id="home pt"

### ISSUE THREAD

**Issue by ytiurin** [gusbemacbe/bootstraphyphen#2]
OK
I see that you do  id="home pt", this is not right, id should be one unique word:  id="home" or  id="pt"

change id any of those variants and update your hyphenation script to accept the correct id

**Comment by gusbemacbe** [comment]
If I want to change id to lang ot class in a Javascript script? It would be easy.

**Comment by gusbemacbe** [comment]
I changed from id to class and I added a language to the class attribute and it did not work.

**Comment by ytiurin** [comment]
@gusbemacbe You actually can apply class="pt" instead of id="pt" and get an element in javascript the next way: 
```javascript
var el = document.getElementsByClassName(id)[0];
```

**Comment by ytiurin** [comment]
So provideHyphenation function will look like
```javascript
         function provideHyphenation(hyphenate, className) 
         {
             var el = document.getElementsByClassName(className)[0];
              el.innerHTML = hyphenate(el.innerHTML);
          }

**Comment by gusbemacbe** [comment]
Do I maintain this same code without modifying the class name?

Or

```
function provideHyphenation(hyphenate, class) 
         {
             var el = document.getElementsByClassName(class)[0];
              el.innerHTML = hyphenate(el.innerHTML);
          }
```

Is it so?

**Comment by ytiurin** [comment]
Right, now add locales to classes like you did with ids before: class="tab-pane pt"

**Comment by gusbemacbe** [comment]
I tested and they are not hyphened in Portuguese and Georgian. :-/

Please, fork again my project, analyse and test the HTML page in your GitHub pages for seeing what happened.

**Comment by ytiurin** [comment]
OK, change hyphenationPatternsNl to hyphenationPatternsDe

**Comment by ytiurin** [comment]
hyphenationPatternsFr => hyphenationPatternsKa
hyphenationPatternsIt => hyphenationPatternsPt

**Comment by gusbemacbe** [comment]
Ah, I did not pay attention to the patterns. Now it worked now. Thank you a lot. 

I have to fix the tabs which are not well aligned vertically. They were well aligned vertically before.

**Comment by ytiurin** [comment]
Yeh, you lost your classes: class="tab-pane" on tab elements

**Comment by ytiurin** [comment]
Or you added tab-pane class to your first tab header, just remove it

**Comment by gusbemacbe** [comment]
Fixed. All issues solved. It works everything. Thank you a lot.
